### ISSUE TITLE
cuda交流 （CUDA communication）

### ISSUE THREAD

**Issue by leoda1** [Min-star07/CUDA#1]
可以一起交流学习吗 我也在学习cuda，我有一个和你这个仓库类似的仓库。（Can we communicate and learn together? I am also learning cuda, and I have a warehouse similar to yours.）

**Comment by Min-star07** [comment]
可以啊，但是我刚开始学，很基础，我都是跟着一个博客学的。发自我的手机-------- 原始邮件 --------发件人： Da Liu ***@***.***>日期： 2024年8月28日周三 09:54收件人： Min-star07/CUDA ***@***.***>抄送： Subscribed ***@***.***>主    题： [Min-star07/CUDA] cuda交流 （CUDA communication） (Issue #1)
可以一起交流学习吗 我也在学习cuda，我有一个和你这个仓库类似的仓库。（Can we communicate and learn together? I am also learning cuda, and I have a warehouse similar to yours.）

**Comment by leoda1** [comment]
哦哦是中国人啊 可以加微信吗 我的微信号是：leoleo135
